### ISSUE TITLE
idba_ud : Segmentation fault 

### ISSUE THREAD

**Issue by chenziwu5** [loneknightpy/idba#46]
Dear Yu Peng
  Thanks for your great tool for assembly the metagenome reads. But when i assembled  a bigger data than before(about 46Gb,150bp paired-end reads),i met some troubles as blow:

> number of threads 50
reads 166504600
long reads 0
extra reads 0
read_length 150
kmer 95
kmers 4043406679 3973976227
merge bubble 74
contigs: 1643 n50: 144 max: 7843 mean: 167 total length: 274971 n80: 107
aligned 14418 reads
confirmed bases: 27136 correct reads: 7834 bases: 3762
kmer 40
kmers 7586101528 7531112438
merge bubble 1564262
contigs: 3213050 n50: 150 max: 20467 mean: 138 total length: 446525742 n80: 110
aligned 226248 reads
confirmed bases: 2332670 correct reads: 27184 bases: 6318
distance mean -nan sd -nan
invalid insert distance
more kmers
... ...
/opt/pbs/dispatcher/mom_priv/jobs/20145.mgmt.SC: line 14: 151550 Segmentation fault      (core dumped) /share/home/yuanqingc/idba-master/bin/idba_ud -r /share/home/yuanqingc/test_data/F7.fa --mink 40 --maxk 150 --step 5 --num_threads 50 --min_contig 1000 --pre_correction -o idba_F7out/

All the local-contig-*.fa file were ampty. and my server have 96x32 Gb RAM can use.my hard disk capacity is about 1.5T
Can you give some suggestions for these troubles

Best regards 
chenziwu

**Comment by chichizhao** [comment]
hi,friend. here i got the same question, did you solve this problem? how did you solve it? i would appriceate it very much, thank you!

here is some information about my problem
number of threads 50
reads 442187424
long reads 0
extra reads 0
read_length 150
kmer 20
kmers 1358728697 1383007787
merge bubble 2862253
contigs: 22892761 n50: 134 max: 1973 mean: 65 total length: 1501473097 n80: 36
aligned 67981939 reads
confirmed bases: 312563523 correct reads: 21543289 bases: 1821430
distance mean -nan sd -nan
invalid insert distance
kmer 30
kmers 1363087010 1369777557
merge bubble 1360552
contigs: 2132901 n50: 7465 max: 75290 mean: 571 total length: 1219679752 n80: 2688
aligned 286675061 reads
confirmed bases: 1094780096 correct reads: 234338621 bases: 18801863
distance mean 61.0069 sd 7216.47
invalid insert distance
kmer 40
kmers 1295973262 1298190021
merge bubble 120003
contigs: 1093115 n50: 14370 max: 169564 mean: 1108 total length: 1211212759 n80: 5377
aligned 294905334 reads
confirmed bases: 1125047372 correct reads: 241708491 bases: 1138255
distance mean -50.4066 sd 14260.5
invalid insert distance
kmer 50
kmers 1261816094 1263728865
merge bubble 64350
contigs: 664113 n50: 19555 max: 182166 mean: 1815 total length: 1205436269 n80: 7678
aligned 300243405 reads
confirmed bases: 1141160357 correct reads: 245522060 bases: 531728
distance mean 1113.02 sd 18788.7
invalid insert distance
kmer 60
kmers 1246167785 1247514085
merge bubble 43268
contigs: 473865 n50: 25100 max: 219342 mean: 2539 total length: 1203596827 n80: 10097
aligned 303759463 reads
confirmed bases: 1149990612 correct reads: 247685048 bases: 351378
distance mean -32.2509 sd 23611.9
invalid insert distance
kmer 70
kmers 1233058292 1233987085
merge bubble 32916
contigs: 369915 n50: 29354 max: 217552 mean: 3252 total length: 1203108621 n80: 11912
aligned 306223562 reads
confirmed bases: 1155007616 correct reads: 248695259 bases: 232844
distance mean 563.184 sd 26822.6
invalid insert distance
kmer 80
kmers 1221379483 1221996248
merge bubble 15869
contigs: 609958 n50: 22776 max: 216695 mean: 2024 total length: 1234996652 n80: 8688
reads 442187424
aligned 305494955 reads
distance mean 568.651 sd 22063.1
invalid insert distance

when the program run into this step, it appear that  “  Segmentation fault (core dumped)”
and a core.19779 file was created in the file folder 
when i use the command " gdb core-file core.19779" 
some information displayed like the below, and the main information is 
"Core was generated by `idba_ud -r SRR13376033in1.fa --maxk 80 --step 10 -o ./idba/ --num_threads 50'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000040e6c9 in ?? () "

And i wonder that it is really some segmentation fault, most probably segments is maxk what i think ( doesn`t  important) 

[New LWP 19779]
[New LWP 25481]
[New LWP 25466]
[New LWP 25482]
[New LWP 25476]
[New LWP 25491]
[New LWP 25492]
[New LWP 25488]
[New LWP 19780]
[New LWP 25509]
[New LWP 25471]
[New LWP 25484]
[New LWP 25508]
[New LWP 25499]
[New LWP 25504]
[New LWP 25486]
[New LWP 25494]
[New LWP 25470]
[New LWP 25514]
[New LWP 25472]
[New LWP 25480]
[New LWP 25501]
[New LWP 25489]
[New LWP 25485]
[New LWP 25478]
[New LWP 25474]
[New LWP 25469]
[New LWP 25467]
[New LWP 25475]
[New LWP 25477]
[New LWP 25483]
[New LWP 25513]
[New LWP 25510]
[New LWP 25479]
[New LWP 25496]
[New LWP 25498]
[New LWP 25503]
[New LWP 25505]
[New LWP 25506]
[New LWP 25493]
[New LWP 25511]
[New LWP 25502]
[New LWP 25490]
[New LWP 25468]
[New LWP 25473]
[New LWP 25507]
[New LWP 25487]
[New LWP 25495]
[New LWP 25500]
[New LWP 25497]
[New LWP 25512]
Core was generated by `idba_ud -r SRR13376033in1.fa --maxk 80 --step 10 -o ./idba/ --num_threads 50'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000040e6c9 in ?? ()

**Comment by jvollme** [comment]
It looks a bit like you only gave it forward reads. Could that be? Idba can only work if it has at least one set of paired reads.

**Comment by chichizhao** [comment]
yes，you are right，but i use the command “fq2fa --merge file1.fq file2.fq filein1.fa” to form the paired reads in one file in fasta form. did I do something wrong？thank you for your respons, I really appreciate it!
